# Generated by Django 5.1.7 on 2025-03-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
