# Generated by Django 5.1.7 on 2025-03-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='photo',
        ),
        migrations.AddField(
            model_name='menusection',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.restaurantdashboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menusection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
