# Generated by Django 5.1.7 on 2025-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_tablebooking_preordered_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdashboard',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_gallery/'),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_gallery/'),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='gallery3',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_gallery/'),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='map_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
