# Generated by Django 5.1.7 on 2025-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_restaurantdashboard_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdashboard',
            name='map_location',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
