# Generated by Django 5.1.7 on 2025-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_restaurantdashboard_khalti_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
