# Generated by Django 5.1.7 on 2025-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
