# Generated by Django 5.1.7 on 2025-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_is_arrived_tablebooking_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
