# Generated by Django 5.1.7 on 2025-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_tablebooking_extra_order_pidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='extra_paid',
            field=models.BooleanField(default=False),
        ),
    ]
