# Generated by Django 5.1.7 on 2025-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_tablebooking_extra_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='final_payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], help_text='How the final bill (including extra orders) was paid.', max_length=10, null=True),
        ),
    ]
