# Generated by Django 5.1.7 on 2025-04-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_tablebooking_final_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('percentage', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_global', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.discount'),
        ),
    ]
