# Generated by Django 5.1.7 on 2025-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_discount_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
