# Generated by Django 5.1.7 on 2025-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_menuitem_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='payatrestaurantpayment',
            name='extra_paid',
            field=models.BooleanField(default=False),
        ),
    ]
