# Generated by Django 5.1.7 on 2025-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_table_tablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdashboard',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
    ]
