# Generated by Django 5.1.7 on 2025-04-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menusection',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dashboard.menu'),
            preserve_default=False,
        ),
    ]
