# Generated by Django 5.1.7 on 2025-04-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_menusection_restaurant_menusection_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='menu',
        ),
        migrations.AddField(
            model_name='menusection',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sections', to='dashboard.restaurantdashboard'),
            preserve_default=False,
        ),
    ]
