# Generated by Django 5.1.7 on 2025-04-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sections', to='dashboard.restaurantdashboard'),
        ),
    ]
