# Generated by Django 5.1.7 on 2025-04-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_menusection_name_alter_menusection_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='dashboard.tablebooking')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.menuitem')),
            ],
        ),
    ]
