# Generated by Django 5.1.7 on 2025-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_restaurantdashboard_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
