# Generated by Django 5.1.7 on 2025-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_tablebooking_paid_tablebooking_payment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='payment_token',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='khalti_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='khalti_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='use_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
