# Generated by Django 5.1.7 on 2025-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_tablebooking_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
