# Generated by Django 5.1.7 on 2025-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_tablebooking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdashboard',
            name='khalti_public_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdashboard',
            name='khalti_secret_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
