# Generated by Django 5.1.7 on 2025-04-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_tablebooking_khalti_pidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
