# Generated by Django 5.1.7 on 2025-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_tablebooking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
