# Generated by Django 5.1.7 on 2025-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_tablebooking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('restaurant', 'Pay at Restaurant')], default='restaurant', max_length=20),
        ),
    ]
