# Generated by Django 5.1.7 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_tablebooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='food_preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
