# Generated by Django 5.1.7 on 2025-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_payatrestaurantpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='extra_order_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
