# Generated by Django 5.1.7 on 2025-04-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_discount_menuitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.restaurantdashboard'),
        ),
    ]
