# Generated by Django 5.1.7 on 2025-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
